version: '3'
services:
  broker:
    build: broker
    ports:
      - "8084:8084"
  auldfellas:
    build: auldfellas
    depends_on:
      - broker
    container_name: auldfellas
  dodgydrivers:
    build: dodgydrivers
    container_name: dodgydrivers
    depends_on:
      - broker
  girlpower:
    build: girlpower
    container_name: girlpower
    depends_on:
      - broker